sdkversion: 6.0.0
name: buildstatus
version: 1.0
vendor: rhomobile
build: release
applog: rholog.txt
javascript_application: true
iphone:
  configuration: Release
  ## Note: sdk can be 3 predefined value : latest, latest_simulator, latest_device
  ## simulator or device detect by rake command for "rake run:iphone" is simulator, for "rake device:iphone:production" is device
  ## sdk also can be defined exactly like:  iphonesimulator10.2 or iphoneos10.2
  sdk: latest
  ## Note: Provisioning
  ## There are two provisioning type for modern XCode: Automatic and Manual
  ## development_team must be configured for any type provisioning
  ## you see team code by run this command:
  ## $ security find-identity -p codesigning -v
  ## you will see list of certificates and you should copy code from "iPhone Distribution" line like this (code is PNQRMU3LPM):
  ## 5) D6D5EE35B3F8D9C04E85C7015539F04B38403DA3 "iPhone Distribution: Vasya Pupkin (PNQRMU3LPM)"
  ##
  ## Note: This is Automatic provisioning configuration:
  #provisioning_style: Automatic
  #development_team: "PNQRMU3LPM"
  ##
  ## Note: This is Manual provisioning configuration:
  ## provisionprofile can be defined as name or UUID - if you defined provisionprofile then codesignidentity defined automatically if you not defined it in this build.yml
  #provisionprofile: "Current WildCart 05"
  #provisioning_style: Manual
  #development_team: "PNQRMU3LPM"
  #codesignidentity: "iPhone Developer"
  ##
  #entitlements:
  BundleIdentifier: com.rhomobile.buildstatus
  BundleURLScheme: buildstatus
  production:
    ipa_itunesartwork_image: "./production/iTunesArtwork.png"
  # Note: Specifies the URL schemes the app is able to call using Rho.System.runApplication
  #ApplicationQueriesSchemes: ["scheme1", "scheme2"]

uwp:
  productid: 'a3393340-a26e-0135-78ba-6716f3918d60'
  target: 'ARM'

android:
  #manifest_template: 'AndroidManifest.erb'
  # Note: in order to simplify debugging only app messages and system channels with priority informative and higher, and any errors are enabled by default
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E

## Note: setup android_title to 0 for remove default window titlebar in Android application
#android_title: 0

wm:
  #sdk: "MC3000c50b (ARMV4I)"
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  extensions:
    - webkit

win32:
  deployqt: 1
  deploymsvc: 1

extensions: []

rhobundle:
  exclude_items:
  - thumb.db
